### ISSUE TITLE
ControlParameters send trigger signals on first tick

### ISSUE THREAD

**Issue by morganpackard** [TonicAudio/Tonic#260]
`context.forceNewOutput` is set to true in the constructor, which results in the code below sending a trigger signal. 

     inline void ControlValue_::computeOutput(const SynthesisContext_ & context){
          output_.triggered =  (changed_ || context.forceNewOutput);
          changed_ = context.forceNewOutput; // if new output forced, don't reset changed status until next tick
          output_.value = value_;
    }

**Comment by morganpackard** [comment]
@ndonald2 do you remember what the purpose of forceNewOutput is? I'm not using it for anything. I'm wondering if it may be more trouble than it's worth.

**Comment by ndonald2** [comment]
It was used to help with the metronome starts, I think,  but it might be deadweight at this point.

**Comment by morganpackard** [comment]
Thanks Nick. The whole triggered thing is a minefield, as I think you know. Really needs to be reconsidered from the ground up, I think.

**Comment by ndonald2** [comment]
Agreed. I think we really need better value types for our "control signals" that are more extensible and functional than just float (value) and bool (triggered).

**Comment by morganpackard** [comment]
We'll hash this out when we're ready for Tonic 2.0! I personally am fine with a much more limited control system. I'm finding that in practice, I wind up slinging quite a lot of plain C++ when I need to actually accomplish anything with Tonic. I'm personally interested in keeping Tonic's core as simple as possible. But we can drink some beer, but on some boxing gloves, and sort this all out some time :)

**Comment by morganpackard** [comment]
Maybe we need to just accept that ControlValues output a trigger on the first tick. I think lots of ControlGenerators depend on that for initializing their own values. This behavior is mainly a problem for ControlCallback, which always triggers on the first tick when a ControlParameter is used as the input. Simpler to just prevent ControlCallback from executing its callback on the first tick.

**Comment by morganpackard** [comment]
Gonna close this issue and reopen one relating to ControlCallback.
