### ISSUE TITLE
Discussion today about past and future of TonicAudio

### ISSUE THREAD

**Issue by hamoid** [TonicAudio/Tonic#277]
The details are here:
https://groups.google.com/forum/#!topic/tonic_audio_users/z-lMzuv1L-8

Date: March 26th 2016
Time: 10AM Eastern Standard Time (4PM CET+1 = Berlin, Madrid...)

Place: https://meet.jit.si/tonicaudio

We will take notes, and close this issue after the talk.

**Comment by morganpackard** [comment]
Awesome. Thanks for setting this up.

**Comment by morganpackard** [comment]
Here's some stuff I want to talk about:
- Hi! Who are all you people?
- testing of development branch with an eye toward merge into master
- status of cmake and cross platform unit tests
- Project roadmap, future, leadership

**Comment by hamoid** [comment]
# TonicAudio call 26.03.2016

Briefly, this is what we discussed in our first call:

We introduced ourselves. @morganpackard, @ukelady and @hamoid.

Guiding principles are still valid: https://github.com/TonicAudio/Tonic/wiki/Guiding-Principles
    
Efficiency: most algorithms have good performance, maybe some like reverb or band-limited
are less efficient. We should try if we need really band limited or not.

Each voice should be able to have its own LFO, not necessarily be in sync. We probably did something wrong in our LFO experiments.

Novocaine is not a requirement for iOS, was there just for convenience.

Tonic is mostly complete and usable. It has been used during the last years for desktop and mobile projects, including museum installations.

Next big feature would be cross platform unit tests.

We will start using the development branch and look at the differences with master. Then we can test the existing pull requests. 

@hamoid might write a short intro tutorial so new users can get started.

**Comment by morganpackard** [comment]
Here's a video tutorial I created a while ago:

https://www.youtube.com/watch?v=ppf3b8BC6yU

On Sun, Mar 27, 2016 at 7:32 AM, Abe Pazos <notifications@github.com> wrote:

> TonicAudio call 26.03.2016
>
> Briefly, this is what we discussed in our first call:
>
> We introduced ourselves. @morganpackard <https://github.com/morganpackard>,
> @ukelady <https://github.com/ukelady> and @hamoid
> <https://github.com/hamoid>.
>
> Guiding principles are still valid:
> https://github.com/TonicAudio/Tonic/wiki/Guiding-Principles
>
> Efficiency: most algorithms have good performance, maybe some like reverb
> or band-limited
> are less efficient. We should try if we need really band limited or not.
>
> Each voice should be able to have its own LFO, not necessarily be in sync.
> We probably did something wrong in our LFO experiments.
>
> Novocaine is not a requirement for iOS, was there just for convenience.
>
> Tonic is mostly complete and usable. It has been used during the last
> years for desktop and mobile projects, including museum installations.
>
> Next big feature would be cross platform unit tests.
>
> We will start using the development branch and look at the differences
> with master. Then we can test the existing pull requests.
>
> @hamoid <https://github.com/hamoid> might write a short intro tutorial so
> new users can get started.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/TonicAudio/Tonic/issues/277#issuecomment-202043663>
>



-- 
===============
Morgan Packard
web: www.morganpackard.com
twitter: @morganpackard
phone: (720) 891-0122
